# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-IMAP-SImple-SSL
version:      1.1
version_from: lib/Net/IMAP/Simple/SSL.pm
installdirs:  site
requires:
    IO::Socket::SSL:               
    Net::IMAP::Simple:             
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
